### ISSUE TITLE
Is there any upcoming event this year?

### ISSUE THREAD

**Issue by amazingandyyy** [nodeschool/stanford#4]
Is there any upcoming event this year?

**Comment by feross** [comment]
Hmm, is there interest in another NodeSchool event at Stanford? If so, I'm happy to organize it.

@nfsiddiqui – which clubs are best to coordinate with to organize this?

**Comment by nfsiddiqui** [comment]
ACM, cs+socialgood, wics - women in computer science

**Comment by feross** [comment]
ACM helped us last time. I'm biased toward using them (since I used to be ACM president when I was at Stanford). But they recently invited a speaker from Palantir, a military contractor that builds software to spy on private communications. 🤢

So probably better to try the other clubs first.

**Comment by abi** [comment]
boooooo military-industrial-academic complex

**Comment by pfe1223** [comment]
Went to my first NodeSchool event yesterday in Oakland. Since I live on the peninsula, I'd love for a closer event.
